export const INDIA_DEMO_CITIES: Array<[string, string]> = [
  ["Surat", "Gujarat"],
  ["Ahmedabad", "Gujarat"],
  ["Vadodara", "Gujarat"],
  ["Rajkot", "Gujarat"],
  ["Bhavnagar", "Gujarat"],
  ["Jamnagar", "Gujarat"],
  ["Gandhinagar", "Gujarat"],
  ["Anand", "Gujarat"],
  ["Mumbai", "Maharashtra"],
  ["Pune", "Maharashtra"],
  ["Nagpur", "Maharashtra"],
  ["Nashik", "Maharashtra"],
  ["Aurangabad", "Maharashtra"],
  ["Kolhapur", "Maharashtra"],
  ["Solapur", "Maharashtra"],
  ["Amravati", "Maharashtra"],
  ["Bengaluru", "Karnataka"],
  ["Mysuru", "Karnataka"],
  ["Mangaluru", "Karnataka"],
  ["Hubballi", "Karnataka"],
  ["Belagavi", "Karnataka"],
  ["Kalaburagi", "Karnataka"],
  ["Shivamogga", "Karnataka"],
  ["Chennai", "Tamil Nadu"],
  ["Coimbatore", "Tamil Nadu"],
  ["Madurai", "Tamil Nadu"],
  ["Tiruchirappalli", "Tamil Nadu"],
  ["Salem", "Tamil Nadu"],
  ["Tiruppur", "Tamil Nadu"],
  ["Erode", "Tamil Nadu"],
  ["Thoothukudi", "Tamil Nadu"],
  ["Kochi", "Kerala"],
  ["Thiruvananthapuram", "Kerala"],
  ["Kozhikode", "Kerala"],
  ["Thrissur", "Kerala"],
  ["Kollam", "Kerala"],
  ["Kannur", "Kerala"],
  ["Hyderabad", "Telangana"],
  ["Warangal", "Telangana"],
  ["Nizamabad", "Telangana"],
  ["Karimnagar", "Telangana"],
  ["Khammam", "Telangana"],
  ["Visakhapatnam", "Andhra Pradesh"],
  ["Vijayawada", "Andhra Pradesh"],
  ["Guntur", "Andhra Pradesh"],
  ["Nellore", "Andhra Pradesh"],
  ["Kurnool", "Andhra Pradesh"],
  ["Tirupati", "Andhra Pradesh"],
  ["Jaipur", "Rajasthan"],
  ["Jodhpur", "Rajasthan"],
  ["Udaipur", "Rajasthan"],
  ["Kota", "Rajasthan"],
  ["Ajmer", "Rajasthan"],
  ["Bikaner", "Rajasthan"],
  ["Alwar", "Rajasthan"],
  ["Lucknow", "Uttar Pradesh"],
  ["Kanpur", "Uttar Pradesh"],
  ["Agra", "Uttar Pradesh"],
  ["Varanasi", "Uttar Pradesh"],
  ["Prayagraj", "Uttar Pradesh"],
  ["Ghaziabad", "Uttar Pradesh"],
  ["Noida", "Uttar Pradesh"],
  ["Meerut", "Uttar Pradesh"],
  ["Bareilly", "Uttar Pradesh"],
  ["Gorakhpur", "Uttar Pradesh"],
  ["Bhopal", "Madhya Pradesh"],
  ["Indore", "Madhya Pradesh"],
  ["Jabalpur", "Madhya Pradesh"],
  ["Gwalior", "Madhya Pradesh"],
  ["Ujjain", "Madhya Pradesh"],
  ["Sagar", "Madhya Pradesh"],
  ["Kolkata", "West Bengal"],
  ["Howrah", "West Bengal"],
  ["Durgapur", "West Bengal"],
  ["Siliguri", "West Bengal"],
  ["Asansol", "West Bengal"],
  ["Kharagpur", "West Bengal"],
  ["Patna", "Bihar"],
  ["Gaya", "Bihar"],
  ["Muzaffarpur", "Bihar"],
  ["Bhagalpur", "Bihar"],
  ["Bhubaneswar", "Odisha"],
  ["Cuttack", "Odisha"],
  ["Rourkela", "Odisha"],
  ["Berhampur", "Odisha"],
  ["Amritsar", "Punjab"],
  ["Ludhiana", "Punjab"],
  ["Jalandhar", "Punjab"],
  ["Patiala", "Punjab"],
  ["Gurugram", "Haryana"],
  ["Faridabad", "Haryana"],
  ["Panipat", "Haryana"],
  ["Hisar", "Haryana"],
  ["New Delhi", "Delhi"],
  ["Guwahati", "Assam"],
  ["Dibrugarh", "Assam"],
  ["Silchar", "Assam"],
  ["Jorhat", "Assam"],
  ["Ranchi", "Jharkhand"],
  ["Jamshedpur", "Jharkhand"],
  ["Dhanbad", "Jharkhand"],
  ["Raipur", "Chhattisgarh"],
  ["Bhilai", "Chhattisgarh"],
  ["Bilaspur", "Chhattisgarh"],
  ["Panaji", "Goa"],
];

const STATE_CENTERS: Record<string, [number, number]> = {
  Gujarat: [22.3, 71.8],
  Maharashtra: [19.7, 75.7],
  Karnataka: [15.3, 75.7],
  "Tamil Nadu": [11.1, 78.6],
  Kerala: [10.3, 76.3],
  Telangana: [17.9, 79.2],
  "Andhra Pradesh": [15.9, 79.7],
  Rajasthan: [27.0, 74.2],
  "Uttar Pradesh": [26.8, 80.9],
  "Madhya Pradesh": [23.5, 78.5],
  "West Bengal": [23.0, 87.8],
  Bihar: [25.8, 85.5],
  Odisha: [20.3, 84.4],
  Punjab: [31.1, 75.3],
  Haryana: [29.1, 76.3],
  Delhi: [28.6, 77.2],
  Assam: [26.2, 92.9],
  Jharkhand: [23.6, 85.3],
  Chhattisgarh: [21.3, 81.8],
  Goa: [15.4, 73.9],
};

export function getIndiaDemoLocation(index: number) {
  const [city, state] = INDIA_DEMO_CITIES[index % INDIA_DEMO_CITIES.length]!;
  const [lat, lng] = STATE_CENTERS[state]!;
  return { city, state, lat: lat + (index % 3) * 0.035, lng: lng + (index % 3) * 0.035 };
}
